### ISSUE TITLE
Popup dialogue min./max. button UI bug

### ISSUE THREAD

**Issue by ghost** [yeyushengfan258/ArcStarry-kde#2]
The min./max. button on a pop up dialogue has a bug.

![SUS-P-2022-01-31-13-47-00](https://user-images.githubusercontent.com/94405857/151800243-22cbf20c-f8d4-4c60-bca0-5417adbd30ed.png)

**Comment by yeyushengfan258** [comment]
It should not be a bug, it should be that there is no interactive change in the area that cannot be selected.

**Comment by ghost** [comment]
Closed because it's intended that there is no interactive change in the area that cannot be selected .
